[binaries]
; Defined in `winsysroot.ini`
; c = 'clang-cl'
; cpp = 'clang-cl'
ar = 'llvm-lib'
ld = 'lld-link'
windres = 'llvm-rc'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
